import AppKit

/// Puts one queue item on the general pasteboard with its data promised, and
/// reports the first time another app asks for it.
///
/// Tested on macOS 26 (2026-10-10): Spotlight's clipboard history reads every
/// change right away, which would look like a paste. It leaves items with the
/// nspasteboard.org markers alone, and so did Chrome and other Chromium apps,
/// which otherwise read the clipboard when they come to the front. Universal
/// Clipboard fetched the file URL of an image item at once until the item was
/// marked as this Mac only.
@MainActor
final class ClipQueuePasteboard: NSObject, NSPasteboardItemDataProvider {
    nonisolated static let markerTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Long enough for an app to read the other types it wants in the same paste.
    static let settleDelay: Duration = .milliseconds(350)
    /// A read this soon after an app comes to the front is that app looking,
    /// not pasting.
    static let activationWindow: TimeInterval = 0.3

    var onPaste: (() -> Void)?
    var onReplace: (() -> Void)?

    private let pasteboard: NSPasteboard

    private var data: [NSPasteboard.PasteboardType: Data] = [:]
    private var placement = 0
    private var handledPlacement = 0
    private var changeCount: Int?
    private var lastActivation = Date.distantPast
    private var pending: Task<Void, Never>?

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var ownsClipboard: Bool {
        changeCount == pasteboard.changeCount
    }

    func place(_ contents: [(NSPasteboard.PasteboardType, Data)]) {
        pending?.cancel()
        pending = nil
        placement += 1
        data = Dictionary(contents, uniquingKeysWith: { first, _ in first })

        let item = NSPasteboardItem()
        item.setDataProvider(self, forTypes: contents.map(\.0))
        for type in Self.markerTypes {
            item.setData(Data(), forType: type)
        }
        // This Mac only: Universal Clipboard otherwise fetches file URLs (the
        // path that comes with an image) right away, which looks like a paste.
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        pasteboard.writeObjects([item])
        changeCount = pasteboard.changeCount
    }

    func reset() {
        pending?.cancel()
        pending = nil
        data = [:]
        changeCount = nil
        handledPlacement = placement
    }

    func noteActivation(at date: Date = Date()) {
        lastActivation = date
    }

    nonisolated func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        // AppKit calls this on the main thread, with an item it owns.
        nonisolated(unsafe) let item = item
        MainActor.assumeIsolated {
            provide(item: item, type: type)
        }
    }

    nonisolated func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}

    private func provide(item: NSPasteboardItem, type: NSPasteboard.PasteboardType) {
        guard let value = data[type] else { return }
        item.setData(value, forType: type)
        guard handledPlacement != placement else { return }
        handledPlacement = placement

        let justActivated = Date().timeIntervalSince(lastActivation) < Self.activationWindow
        pending = Task { [weak self] in
            try? await Task.sleep(for: Self.settleDelay)
            guard !Task.isCancelled, let self else { return }
            self.pending = nil
            if justActivated {
                // The data is now cached on the pasteboard, so a real paste of
                // this item would go unnoticed. Put the same item back instead.
                self.onReplace?()
            } else {
                self.onPaste?()
            }
        }
    }
}
